### ISSUE TITLE
Raw frames not available.

### ISSUE THREAD

**Issue by nanoxas** [Tsunehiko/generate-commentary#3]
Hi Tsunehiko, I was checking your paper and dataset. Impressive results!. Would you be so kind to upload the raw frames as well for the splits you already made for your features. If you already did upload them could you tell me how I could access them?

**Comment by tsunehiko** [comment]
@nanoxas Thank you for your interest! I used all videos from YouTube playlists (e.g. https://www.youtube.com/playlist?list=PLPZ7h6L6LC7VTeQ753LhTrgLEcLSU3fpT), but some playlists has already been not active. You could not access directly these videos used in the dataset, but you can get the features extracted by Video Understanding model. Please access https://tsunehiko.github.io/lol-v2t/
